version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "HelloLambdaJava"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1czdcsxxmvotv"
s3_prefix = "HelloLambdaJava"
region = "eu-north-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
